export default {
  // Colors

  PRIMARY_FADE: "#FF006E",
  PRIMARY_BLUE: "#3A86FF",
  PRIMARY_LILA: "#8338EC",
  PRIMARY_ORANGE: "#FB5607",
  SECONDARY_PINK: "#FF006E",
  SECONDARY_YELLOW: "#FFBE0B",
  NEUTRAL_WHITE: "#FFFFFF",
  NEUTRAL_GREY: "#B7B7B7",
  NEUTRAL_BLACK: "#200E38",
  ALERT_ERROR: "#F24655",
  ALERT_SUCCESS: "#47D7B2",

  // Values
  BORDER_CURVE: 8,
  BORDER_ROUND: 20,
  BORDER_CIRCLE: 100,

  // Fonts
  FONT_SIZE_EXTRA_LARGE: 20,
  FONT_SIZE_LARGE: 17,
  FONT_SIZE_NORMAL: 16,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_EXTRA_SMALL: 12,

  FONT_WEIGHT_HEAVY: "900",
  FONT_WEIGHT_BOLDER: "700",
  FONT_WEIGHT_BOLD: "500",
  FONT_WEIGHT_NORMAL: "400",

  // Dimensions
  HORIZONTAL_MARGIN: 18,
  SPACE_NORMAL: 10,
  SPACE_MEDIUM: 15,
  SPACE_LARGE: 20,
  SPACE_EXTRA_LARGER: 30
};
